apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: website
  name: website
spec:
  replicas: 1
  selector:
    matchLabels:
      component: website
  template:
    metadata:
      labels:
        component: website
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
          - name: index
            mountPath: /usr/share/nginx/html
      volumes:
        - name: index
          configMap:
            name: website-configmap