apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- ../../2.9.6
- ingress-http.yaml
- ingress-grpc.yaml

patches:
# webbased shell
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: Role
    name: argocd-server
  path: argocd-server-role.yaml
# webbased shell
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRole
    name: argocd-server
  path: argocd-server-role.yaml

configMapGenerator:
# ingress
- behavior: merge
  literals:
  - server.insecure="true"
  name: argocd-cmd-params-cm
# webbased shell
- behavior: merge
  literals:
  - exec.enabled="true"
  name: argocd-cm
